version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: floiint_multi_db
    ports:
      - "20300:27017"
    volumes:
      - /Volumes/Public/Floiint/databases/multimedia:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword