const BULK_TEST_COORDINATE = "BULK_TEST_COORDINATE";
const BULK_LOAD_SEX_ORIENTATIONS = "BULK_LOAD_SEX_ORIENTATIONS";
const BULK_LOAD_TYPE_RELATIONSHIPS = "BULK_LOAD_TYPE_RELATIONSHIPS";
const BUKL_PUT_ALL_SOCIAL_NETWORKS = "BUKL_PUT_ALL_SOCIAL_NETWORKS";


module.exports = {
    BULK_TEST_COORDINATE,
    BULK_LOAD_SEX_ORIENTATIONS,
    BULK_LOAD_TYPE_RELATIONSHIPS,
    BUKL_PUT_ALL_SOCIAL_NETWORKS


}
