const BULK_TEST_COORDINATE = "BULK_TEST_COORDINATE";
const BULK_LOAD_SEX_ORIENTATIONS = "BULK_LOAD_SEX_ORIENTATIONS";
const BULK_LOAD_TYPE_RELATIONSHIPS = "BULK_LOAD_TYPE_RELATIONSHIPS";
const BUKL_PUT_ALL_SOCIAL_NETWORKS = "BUKL_PUT_ALL_SOCIAL_NETWORKS";
const BULK_PUT_ALL_HOBBIES = "BULK_PUT_ALL_HOBBIES";
const BULK_PUT_ALL_GENDERS = "BULK_PUT_ALL_GENDERS";
const BULK_POPULATE_USERS = "BULK_POPULATE_USERS";


module.exports = {
    BULK_TEST_COORDINATE,
    BULK_LOAD_SEX_ORIENTATIONS,
    BULK_LOAD_TYPE_RELATIONSHIPS,
    BUKL_PUT_ALL_SOCIAL_NETWORKS,
    BULK_PUT_ALL_HOBBIES,
    BULK_PUT_ALL_GENDERS,
    BULK_POPULATE_USERS
    


}
