//PUT
const PUT_USER = "PUT_USER";
const PUT_ALL_SOCIAL_NETWORKS = "PUT_ALL_SOCIAL_NETWORKS";
const PUT_USER_FLIRT_BY_USER_ID = "PUT_USER_FLIRT_BY_USER_ID";
const PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID = "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID";

//UPDATE
const UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID = "UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_USER_NETWORK_BY_USER_ID = "UPDATE_USER_NETWORK_BY_USER_ID";
const UPDATE_USER_INTERESTS_BY_USER_ID = "UPDATE_USER_INTERESTS_BY_USER_ID";
const UPDATE_USER_QRS_BY_USER_ID = "UPDATE_USER_QRS_BY_USER_ID";
const UPDATE_USER_BIOGRAPHY_BY_USER_ID = "UPDATE_USER_BIOGRAPHY_BY_USER_ID"
const UPDATE_USER_HOBBIES_BY_USER_ID = "UPDATE_USER_HOBBIES_BY_USER_ID";

//GET
const GET_ALL_SOCIAL_NETWORKS = "GET_ALL_SOCIAL_NETWORKS";
const GET_USER_CONTACTS_BY_USER_ID = "GET_USER_CONTACTS_BY_USER_ID";
const GET_USER_FLIRTS = "GET_USER_FLIRTS";
const GET_USER_IMAGES_BY_USER_ID = "GET_USER_IMAGES_BY_USER_ID";
const GET_USER_BY_DISTANCE_FROM_POINT = "GET_USER_BY_DISTANCE_FROM_POINT";
const GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS = "GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS";
const GET_ALL_HOBBIES = "GET_ALL_HOBBIES";
const GET_USER_AUDIOS_BY_USER_ID = "GET_USER_AUDIOS_BY_USER_ID";


//REMOVE
const REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID = "REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID";
const REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID = "REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID";
const REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID = "REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID";


//OTHERS
const DO_LOGIN = "DO_LOGIN";

module.exports = {
    PUT_USER,
    UPDATE_USER,
    DO_LOGIN,
    GET_ALL_SOCIAL_NETWORKS,
    PUT_ALL_SOCIAL_NETWORKS,
    PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID,
    REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID,
    GET_USER_CONTACTS_BY_USER_ID,
    GET_USER_BY_DISTANCE_FROM_POINT,
    UPDATE_USER_NETWORK_BY_USER_ID,
    GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS,
    UPDATE_USER_INTERESTS_BY_USER_ID,
    UPDATE_USER_QRS_BY_USER_ID, 
    PUT_USER_FLIRT_BY_USER_ID,
    UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID,
    GET_USER_FLIRTS,
    GET_USER_IMAGES_BY_USER_ID,
    REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID,
    UPDATE_USER_BIOGRAPHY_BY_USER_ID,
    GET_ALL_HOBBIES,
    UPDATE_USER_HOBBIES_BY_USER_ID,
    GET_USER_AUDIOS_BY_USER_ID,
    REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID

}
