//PUT
const PUT_USER = "PUT_USER";
const PUT_ALL_SOCIAL_NETWORKS = "PUT_ALL_SOCIAL_NETWORKS";
const PUT_USER_FLIRT_BY_USER_ID = "PUT_USER_FLIRT_BY_USER_ID";
const PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID =
  "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID";

const PUT_MESSAGE_TO_USER_WITH_USER_ID = "PUT_MESSAGE_TO_USER_WITH_USER_ID";

//UPDATE
const UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID =
  "UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID";
const UPDATE_USER = "UPDATE_USER";
const UPDATE_USER_NETWORK_BY_USER_ID = "UPDATE_USER_NETWORK_BY_USER_ID";
const UPDATE_USER_INTERESTS_BY_USER_ID = "UPDATE_USER_INTERESTS_BY_USER_ID";
const UPDATE_USER_QRS_BY_USER_ID = "UPDATE_USER_QRS_BY_USER_ID";
const UPDATE_USER_BIOGRAPHY_BY_USER_ID = "UPDATE_USER_BIOGRAPHY_BY_USER_ID";
const UPDATE_USER_HOBBIES_BY_USER_ID = "UPDATE_USER_HOBBIES_BY_USER_ID";
const UPDATE_USER_NAME_BY_USER_ID = "UPDATE_USER_NAME_BY_USER_ID";
const UPDATE_USER_IMAGE_PROFILE_BY_USER_ID =
  "UPDATE_USER_IMAGE_PROFILE_BY_USER_ID";

const UPDATE_SMART_POINT_STATUS_BY_POINT_ID = "UPDATE_SMART_POINT_STATUS_BY_POINT_ID";


const UPDATE_USER_SCANNED_BY_USER_ID = "UPDATE_USER_SCANNED_BY_USER_ID";
const UPDATE_USER_SCANNER_BY_USER_ID = "UPDATE_USER_SCANNER_BY_USER_ID";
const UPDATE_USER_DEFAULT_QR_BY_USER_ID = "UPDATE_USER_DEFAULT_QR_BY_USER_ID";
const UPDATE_USER_RADIO_VISIBILITY_BY_USER_ID = "UPDATE_USER_RADIO_VISIBILITY_BY_USER_ID";
const UPDATE_USER_GENDER_BY_USER_ID = "UPDATE_USER_GENDER_BY_USER_ID";
const PUT_SMART_POINT_BY_USER_ID = "PUT_SMART_POINT_BY_USER_ID";

//GET
const GET_ALL_SOCIAL_NETWORKS = "GET_ALL_SOCIAL_NETWORKS";
const GET_USER_CONTACTS_BY_USER_ID = "GET_USER_CONTACTS_BY_USER_ID";
const GET_USER_FLIRTS = "GET_USER_FLIRTS";
const GET_USER_IMAGES_BY_USER_ID = "GET_USER_IMAGES_BY_USER_ID";
const GET_USER_BY_DISTANCE_FROM_POINT = "GET_USER_BY_DISTANCE_FROM_POINT";
const GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS =
  "GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS";
const GET_ALL_HOBBIES = "GET_ALL_HOBBIES";
const GET_USER_AUDIOS_BY_USER_ID = "GET_USER_AUDIOS_BY_USER_ID";
const GET_USER_QR_BY_USER_ID = "GET_USER_QR_BY_USER_ID";
const GET_ALL_USER_MATCHS_BY_USER_ID = "GET_ALL_USER_MATCHS_BY_USER_ID";
const GET_ACTIVE_FLIRTS_FROM_POINT_AND_TENDENCY = "GET_ACTIVE_FLIRTS_FROM_POINT_AND_TENDENCY";
const GET_ALL_GENDERS = "GET_ALL_GENDERS";
const GET_CHATROOM_MESSAGES_BY_MATCH_ID = "GET_CHATROOM_MESSAGES_BY_MATCH_ID";
const GET_USER_PUBLIC_PROFILE_BY_USER_ID = "GET_USER_PUBLIC_PROFILE_BY_USER_ID";
const GET_PROTECTED_IMAGES_URLS_BY_USER_ID = "GET_PROTECTED_IMAGES_URLS_BY_USER_ID";
const GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID = "GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID";
const REMOVE_PENDING_CHAT_MESSGES_BY_USER_ID_SENDER_ID = "REMOVE_PENDING_CHAT_MESSGES_BY_USER_ID_SENDER_ID";




//REMOVE
const REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID =
  "REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID";
const REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID =
  "REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID";
const REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID =
  "REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID";

const DELETE_CHATROOM_FROM_MATCH_ID_USER_ID = "DELETE_CHATROOM_FROM_MATCH_ID_USER_ID";
const DISABLE_MATCH_BY_MATCH_ID_USER_ID = "DISABLE_MATCH_BY_MATCH_ID_USER_ID";
//OTHERS
const DO_LOGIN = "DO_LOGIN";
const TOKEN_LOGIN = "TOKEN_LOGIN";

module.exports = {
  PUT_USER,
  UPDATE_USER,
  DO_LOGIN,
  GET_ALL_SOCIAL_NETWORKS,
  PUT_ALL_SOCIAL_NETWORKS,
  PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID,
  REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID,
  GET_USER_CONTACTS_BY_USER_ID,
  GET_USER_BY_DISTANCE_FROM_POINT,
  UPDATE_USER_NETWORK_BY_USER_ID,
  GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS,
  UPDATE_USER_INTERESTS_BY_USER_ID,
  UPDATE_USER_QRS_BY_USER_ID,
  PUT_USER_FLIRT_BY_USER_ID,
  UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID,
  GET_USER_FLIRTS,
  GET_USER_IMAGES_BY_USER_ID,
  REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID,
  UPDATE_USER_BIOGRAPHY_BY_USER_ID,
  GET_ALL_HOBBIES,
  UPDATE_USER_HOBBIES_BY_USER_ID,
  GET_USER_AUDIOS_BY_USER_ID,
  REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID,
  TOKEN_LOGIN,
  UPDATE_USER_NAME_BY_USER_ID,
  UPDATE_USER_IMAGE_PROFILE_BY_USER_ID,
  UPDATE_USER_SCANNED_BY_USER_ID,
  UPDATE_USER_SCANNER_BY_USER_ID,
  UPDATE_USER_DEFAULT_QR_BY_USER_ID,
  GET_USER_QR_BY_USER_ID,
  GET_ALL_USER_MATCHS_BY_USER_ID,
  PUT_MESSAGE_TO_USER_WITH_USER_ID,
  GET_ACTIVE_FLIRTS_FROM_POINT_AND_TENDENCY,
  UPDATE_USER_RADIO_VISIBILITY_BY_USER_ID,
  GET_ALL_GENDERS,
  UPDATE_USER_GENDER_BY_USER_ID,
  GET_CHATROOM_MESSAGES_BY_MATCH_ID,
  DELETE_CHATROOM_FROM_MATCH_ID_USER_ID,
  DISABLE_MATCH_BY_MATCH_ID_USER_ID,
  GET_USER_PUBLIC_PROFILE_BY_USER_ID,
  GET_PROTECTED_IMAGES_URLS_BY_USER_ID,
  GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID,
  REMOVE_PENDING_CHAT_MESSGES_BY_USER_ID_SENDER_ID,
  PUT_SMART_POINT_BY_USER_ID,
  UPDATE_SMART_POINT_STATUS_BY_POINT_ID
};
