const PUT_USER = "PUT_USER";
const UPDATE_USER = "UPDATE_USER";
const DO_LOGIN = "DO_LOGIN";
const PUT_USER_QR_BY_USER_ID = "PUT_USER_QR_BY_USER_ID";
const GET_USER_QR_BY_USER_ID = "GET_USER_QR_BY_USER_ID";
const DELETE_USER_QR_BY_USER_ID_QR_ID = "DELETE_USER_QR_BY_USER_ID_QR_ID";
const GET_ALL_SOCIAL_NETWORKS = "GET_ALL_SOCIAL_NETWORKS";
const PUT_ALL_SOCIAL_NETWORKS = "PUT_ALL_SOCIAL_NETWORKS";
const REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID = "REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID";
const GET_USER_CONTACTS_BY_USER_ID = "GET_USER_CONTACTS_BY_USER_ID";
const PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID = "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID";
const GET_USER_BY_DISTANCE_FROM_POINT = "GET_USER_BY_DISTANCE_FROM_POINT";
const UPDATE_USER_BY_USER_ID = "UPDATE_USER_BY_USER_ID";



module.exports = {
    PUT_USER,
    UPDATE_USER,
    DO_LOGIN,
    PUT_USER_QR_BY_USER_ID,
    GET_USER_QR_BY_USER_ID,
    DELETE_USER_QR_BY_USER_ID_QR_ID,
    GET_ALL_SOCIAL_NETWORKS,
    PUT_ALL_SOCIAL_NETWORKS,
    PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID,
    REMOVE_USER_CONTACT_BY_USER_ID_CONTACT_ID,
    GET_USER_CONTACTS_BY_USER_ID,
    GET_USER_BY_DISTANCE_FROM_POINT,
    UPDATE_USER_BY_USER_ID


}
