const jsonHeaders = {
  'Content-Type': 'application/json', // Define el tipo de contenido como JSON
};
const HOST_API = {
  "dev_ip": "192.168.2.206",
  "dev_port": 3000,
  "pro_ip": "",
  "pro_host": ""
};

const HOST_AUTH = {
  "dev_ip": "192.168.2.206",
  "dev_port": 5500,
  "pro_ip": "",
  "pro_host": "",
  "endpoint_login": "/login",
  "endpoint_register": "/register",
  
};

const HOST_CHAT = {
  "dev_ip": "192.168.2.206",
  "dev_port": 4000,
  "pro_ip": "",
  "pro_host": ""
};

const HOST_MULT = {
  "dev_ip": "192.168.2.206",
  "dev_port": 7000,
  "pro_ip": "",
  "pro_host": ""
};

// const String _DEV_HOST_IP = "192.168.2.206";
String BASE_AUTH_URL = "http://${HOST_AUTH["dev_ip"]}:${HOST_AUTH["dev_port"]}";

// const String _DEV_HOST = "http://$_DEV_HOST_IP:3000";
// const String _HOST = _DEV_HOST;

// const String BASE_API_URL = "$_HOST/api";
// const String BASE_AUTH_URL = "$_HOST/auth";
// const String BASE_UPLOAD_IMAGE_URL = "$_HOST/upload/image";
// const String BASE_UPLOAD_AUDIO_URL = "$_HOST/upload/audio";
// const String BASE_PROTECTED_IMAGE_URL = "$_HOST/protected-image";

// const String SERVER_API = BASE_API_URL;
// const String SERVER_AUTH = BASE_AUTH_URL;
// const String SERVER_UPLOAD_IMAGE = BASE_UPLOAD_IMAGE_URL;
// const String SERVER_UPLOAD_AUDIO = BASE_UPLOAD_AUDIO_URL;

class HostActionsItem {
  String action;
  String url;
  String path;
  HostActionsItem(this.action, this.url, this.path);
  String build() => url + path;
}

final HostActionsItem Login = HostActionsItem(
    "LOGIN", BASE_AUTH_URL, HOST_AUTH["endpoint_login"].toString());


class HostActionV2{
  static final HostActionsItem login = HostActionsItem(
    "LOGIN", BASE_AUTH_URL, HOST_AUTH["endpoint_login"].toString());

    static final HostActionsItem register = HostActionsItem(
    "REGISTER", BASE_AUTH_URL, HOST_AUTH["endpoint_register"].toString());
}




enum HostActions {
  LOGIN("", "BASE_AUTH_URL"),

  REGISTER("PUT_USER", "SERVER_AUTH"),
  GET_USER_QR_BY_USER_ID("GET_USER_QR_BY_USER_ID", "SERVER_API"),
  GET_USER_BY_DISTANCE_FROM_POINT(
      "GET_USER_BY_DISTANCE_FROM_POINT", "SERVER_API"),
  GET_ALL_SOCIAL_NETWORKS("GET_ALL_SOCIAL_NETWORKS", "SERVER_API"),
  GET_ALL_GENDERS("GET_ALL_GENDERS", "SERVER_API"),
  UPDATE_USER_NETWORK_BY_USER_ID(
      "UPDATE_USER_NETWORK_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_INTERESTS_BY_USER_ID(
      "UPDATE_USER_INTERESTS_BY_USER_ID", "SERVER_API"),
  GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS(
      "GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS", "SERVER_API"),

  GET_ALL_USER_MATCHS_BY_USER_ID(
      "GET_ALL_USER_MATCHS_BY_USER_ID", "SERVER_API"),

  UPDATE_USER_QRS_BY_USER_ID("UPDATE_USER_QRS_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_SEARCHING_RANGE_BY_USER_ID(
      "UPDATE_USER_SEARCHING_RANGE_BY_USER_ID", "SERVER_API"),

  UPDATE_USER_NAME_BY_USER_ID("UPDATE_USER_NAME_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_RADIO_VISIBILITY(
      "UPDATE_USER_RADIO_VISIBILITY_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_GENDER_BY_USER_ID("UPDATE_USER_GENDER_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_DEFAULT_QR_BY_USER_ID(
      "UPDATE_USER_DEFAULT_QR_BY_USER_ID", "SERVER_API"),

  UPDATE_USER_IMAGE_PROFILE_BY_USER_ID(
      "UPDATE_USER_IMAGE_PROFILE_BY_USER_ID", "SERVER_API"),
  PUT_USER_LOCATION_BY_USER_FLIRT(
      "PUT_USER_LOCATION_BY_USER_FLIRT", "SERVER_API"),
  PUT_USER_FLIRT_BY_USER_ID("PUT_USER_FLIRT_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID(
      "UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID", "SERVER_API"),
  GET_USER_FLIRTS("GET_USER_FLIRTS", "SERVER_API"),
  PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID(
      "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID", "SERVER_API"),
  UPLOAD_IMAGE_BY_USER_ID("", "SERVER_UPLOAD_IMAGE"),
  UPLOAD_AUDIO_BY_USER_ID("", "SERVER_UPLOAD_AUDIO"),

  GET_USER_IMAGES_BY_USER_ID("GET_USER_IMAGES_BY_USER_ID", "SERVER_API"),
  GET_USER_AUDIOS_BY_USER_ID("GET_USER_AUDIOS_BY_USER_ID", "SERVER_API"),

  REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID(
      "REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID", "SERVER_API"),
  REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID(
      "REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID", "SERVER_API"),
  UPDATE_USER_BIOGRAPHY_BY_USER_ID(
      "UPDATE_USER_BIOGRAPHY_BY_USER_ID", "SERVER_API"),
  UPDATE_USER_HOBBIES_BY_USER_ID(
      "UPDATE_USER_HOBBIES_BY_USER_ID", "SERVER_API"),
  GET_ALL_HOBBIES("GET_ALL_HOBBIES", "SERVER_API"),

  GET_CHATROOM_MESSAGES_BY_MATCH_ID(
      "GET_CHATROOM_MESSAGES_BY_MATCH_ID", "SERVER_API"),
  DELETE_CHATROOM_FROM_MATCH_ID_USER_ID(
      "DELETE_CHATROOM_FROM_MATCH_ID_USER_ID", "SERVER_API"),
  PUT_MESSAGE_TO_USER_WITH_USER_ID(
      "PUT_MESSAGE_TO_USER_WITH_USER_ID", "SERVER_API"),

  DISABLE_MATCH_BY_MATCH_ID_USER_ID(
      "DISABLE_MATCH_BY_MATCH_ID_USER_ID", "SERVER_API"),

  GET_USER_PUBLIC_PROFILE_BY_USER_ID(
      "GET_USER_PUBLIC_PROFILE_BY_USER_ID", "SERVER_API"),

  GET_PROTECTED_IMAGES_URLS_BY_USER_ID(
      "GET_PROTECTED_IMAGES_URLS_BY_USER_ID", "SERVER_API"),
  GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID(
      "GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID", "SERVER_API"),

  SOCKET_LISTEN("", "_HOST"),

  // REGISTER("PUT_USER", SERVER_AUTH),
  // GET_USER_QR_BY_USER_ID("GET_USER_QR_BY_USER_ID", SERVER_API),
  // GET_USER_BY_DISTANCE_FROM_POINT(
  //     "GET_USER_BY_DISTANCE_FROM_POINT", SERVER_API),
  // GET_ALL_SOCIAL_NETWORKS("GET_ALL_SOCIAL_NETWORKS", SERVER_API),
  // GET_ALL_GENDERS("GET_ALL_GENDERS", SERVER_API),
  // UPDATE_USER_NETWORK_BY_USER_ID("UPDATE_USER_NETWORK_BY_USER_ID", SERVER_API),
  // UPDATE_USER_INTERESTS_BY_USER_ID(
  //     "UPDATE_USER_INTERESTS_BY_USER_ID", SERVER_API),
  // GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS(
  //     "GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS", SERVER_API),

  // GET_ALL_USER_MATCHS_BY_USER_ID("GET_ALL_USER_MATCHS_BY_USER_ID", SERVER_API),

  // UPDATE_USER_QRS_BY_USER_ID("UPDATE_USER_QRS_BY_USER_ID", SERVER_API),
  // UPDATE_USER_SEARCHING_RANGE_BY_USER_ID(
  //     "UPDATE_USER_SEARCHING_RANGE_BY_USER_ID", SERVER_API),

  // UPDATE_USER_NAME_BY_USER_ID("UPDATE_USER_NAME_BY_USER_ID", SERVER_API),
  // UPDATE_USER_RADIO_VISIBILITY(
  //     "UPDATE_USER_RADIO_VISIBILITY_BY_USER_ID", SERVER_API),
  // UPDATE_USER_GENDER_BY_USER_ID("UPDATE_USER_GENDER_BY_USER_ID", SERVER_API),
  // UPDATE_USER_DEFAULT_QR_BY_USER_ID(
  //     "UPDATE_USER_DEFAULT_QR_BY_USER_ID", SERVER_API),

  // UPDATE_USER_IMAGE_PROFILE_BY_USER_ID(
  //     "UPDATE_USER_IMAGE_PROFILE_BY_USER_ID", SERVER_API),
  // PUT_USER_LOCATION_BY_USER_FLIRT(
  //     "PUT_USER_LOCATION_BY_USER_FLIRT", SERVER_API),
  // PUT_USER_FLIRT_BY_USER_ID("PUT_USER_FLIRT_BY_USER_ID", SERVER_API),
  // UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID(
  //     "UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID", SERVER_API),
  // GET_USER_FLIRTS("GET_USER_FLIRTS", SERVER_API),
  // PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID(
  //     "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID", SERVER_API),
  // UPLOAD_IMAGE_BY_USER_ID("", SERVER_UPLOAD_IMAGE),
  // UPLOAD_AUDIO_BY_USER_ID("", SERVER_UPLOAD_AUDIO),

  // GET_USER_IMAGES_BY_USER_ID("GET_USER_IMAGES_BY_USER_ID", SERVER_API),
  // GET_USER_AUDIOS_BY_USER_ID("GET_USER_AUDIOS_BY_USER_ID", SERVER_API),

  // REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID(
  //     "REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID", SERVER_API),
  // REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID(
  //     "REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID", SERVER_API),
  // UPDATE_USER_BIOGRAPHY_BY_USER_ID(
  //     "UPDATE_USER_BIOGRAPHY_BY_USER_ID", SERVER_API),
  // UPDATE_USER_HOBBIES_BY_USER_ID("UPDATE_USER_HOBBIES_BY_USER_ID", SERVER_API),
  // GET_ALL_HOBBIES("GET_ALL_HOBBIES", SERVER_API),

  // GET_CHATROOM_MESSAGES_BY_MATCH_ID(
  //     "GET_CHATROOM_MESSAGES_BY_MATCH_ID", SERVER_API),
  // DELETE_CHATROOM_FROM_MATCH_ID_USER_ID(
  //     "DELETE_CHATROOM_FROM_MATCH_ID_USER_ID", SERVER_API),
  // PUT_MESSAGE_TO_USER_WITH_USER_ID(
  //     "PUT_MESSAGE_TO_USER_WITH_USER_ID", SERVER_API),

  // DISABLE_MATCH_BY_MATCH_ID_USER_ID(
  //     "DISABLE_MATCH_BY_MATCH_ID_USER_ID", SERVER_API),

  // GET_USER_PUBLIC_PROFILE_BY_USER_ID(
  //     "GET_USER_PUBLIC_PROFILE_BY_USER_ID", SERVER_API),

  // GET_PROTECTED_IMAGES_URLS_BY_USER_ID(
  //     "GET_PROTECTED_IMAGES_URLS_BY_USER_ID", SERVER_API),
  // GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID(
  //     "GET_USER_PROTECTED_URL_FOR_FILE_ID_USER_ID", SERVER_API),

  // SOCKET_LISTEN("", _HOST),
  ;

  final String action;
  final String url;

  const HostActions(this.action, this.url);
}
