const jsonHeaders = {
  'Content-Type': 'application/json', // Define el tipo de contenido como JSON
};

const String _DEV_HOST_IP = "192.168.2.90";
const String _DEV_HOST = "http://$_DEV_HOST_IP:3000";
const String _HOST = _DEV_HOST;

const String BASE_API_URL = "$_HOST/api";
const String BASE_AUTH_URL = "$_HOST/auth";
const String BASE_UPLOAD_IMAGE_URL = "$_HOST/upload/image";
const String BASE_UPLOAD_AUDIO_URL = "$_HOST/upload/audio";
const String BASE_PROTECTED_IMAGE_URL = "$_HOST/protected-image";

const String SERVER_API = BASE_API_URL;
const String SERVER_AUTH = BASE_AUTH_URL;
const String SERVER_UPLOAD_IMAGE = BASE_UPLOAD_IMAGE_URL;
const String SERVER_UPLOAD_AUDIO = BASE_UPLOAD_AUDIO_URL;




enum HostActions {
  LOGIN("DO_LOGIN", SERVER_AUTH),
  REGISTER("PUT_USER", SERVER_AUTH),
  GET_USER_QR_BY_USER_ID("GET_USER_QR_BY_USER_ID", SERVER_API),
  GET_USER_BY_DISTANCE_FROM_POINT(
      "GET_USER_BY_DISTANCE_FROM_POINT", SERVER_API),
  GET_ALL_SOCIAL_NETWORKS("GET_ALL_SOCIAL_NETWORKS", SERVER_API),
  UPDATE_USER_NETWORK_BY_USER_ID("UPDATE_USER_NETWORK_BY_USER_ID", SERVER_API),
  UPDATE_USER_INTERESTS_BY_USER_ID(
      "UPDATE_USER_INTERESTS_BY_USER_ID", SERVER_API),
  GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS(
      "GET_ALL_SEXUAL_ORIENTATIONS_RELATIONSHIPS", SERVER_API),
  UPDATE_USER_QRS_BY_USER_ID("UPDATE_USER_QRS_BY_USER_ID", SERVER_API),
  UPDATE_USER_SEARCHING_RANGE_BY_USER_ID(
      "UPDATE_USER_SEARCHING_RANGE_BY_USER_ID", SERVER_API),

UPDATE_USER_NAME_BY_USER_ID(
      "UPDATE_USER_NAME_BY_USER_ID", SERVER_API),


UPDATE_USER_IMAGE_PROFILE_BY_USER_ID("UPDATE_USER_IMAGE_PROFILE_BY_USER_ID", SERVER_API),
  PUT_USER_LOCATION_BY_USER_FLIRT(
      "PUT_USER_LOCATION_BY_USER_FLIRT", SERVER_API),
  PUT_USER_FLIRT_BY_USER_ID("PUT_USER_FLIRT_BY_USER_ID", SERVER_API),
  UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID(
      "UPDATE_USER_FLIRT_BY_USER_ID_FLIRT_ID", SERVER_API),
  GET_USER_FLIRTS("GET_USER_FLIRTS", SERVER_API),
  PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID(
      "PUT_USER_CONTACT_BY_USER_ID_CONTACT_ID_QR_ID", SERVER_API),
  UPLOAD_IMAGE_BY_USER_ID("", SERVER_UPLOAD_IMAGE),
  UPLOAD_AUDIO_BY_USER_ID("", SERVER_UPLOAD_AUDIO),

  GET_USER_IMAGES_BY_USER_ID("GET_USER_IMAGES_BY_USER_ID", SERVER_API),
  GET_USER_AUDIOS_BY_USER_ID("GET_USER_AUDIOS_BY_USER_ID", SERVER_API),


  REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID("REMOVE_USER_IMAGES_BY_USER_ID_IMAGE_ID", SERVER_API),
  REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID("REMOVE_USER_AUDIO_BY_USER_ID_AUDIO_ID", SERVER_API),
  UPDATE_USER_BIOGRAPHY_BY_USER_ID("UPDATE_USER_BIOGRAPHY_BY_USER_ID", SERVER_API),
  UPDATE_USER_HOBBIES_BY_USER_ID("UPDATE_USER_HOBBIES_BY_USER_ID", SERVER_API),
  GET_ALL_HOBBIES("GET_ALL_HOBBIES", SERVER_API),

  SOCKET_LISTEN("", _HOST),
  ;

  final String action;
  final String url;

  const HostActions(this.action, this.url);
}
