FROM public.ecr.aws/lambda/nodejs:18


# COPY /Users/sierra/Desktop/Projects/Personal/Fl1rPo1nt/server/src ./
# COPY /Users/sierra/Desktop/Projects/Personal/Fl1rPo1nt/server/node_modules/ ./ 
COPY ./Users/sierra/Desktop/Projects/Personal/Fl1rPo1nt/server/package.json ./

# CMD ["src/handler_api.handler"]