version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: floiint_api_db
    ports:
      - "20100:27017"
    user: "999:999"
    volumes:
      - /Volumes/Public/Floiint/databases/api:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword